// <auto-generated />
using System;
using KennelTrace.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KennelTrace.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(KennelTraceDbContext))]
    partial class KennelTraceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KennelTrace.Domain.Features.Animals.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnimalId"));

                    b.Property<string>("AnimalNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Breed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Sex")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Species")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Dog");

                    b.HasKey("AnimalId");

                    b.HasIndex("AnimalNumber")
                        .IsUnique()
                        .HasDatabaseName("UQ_Animals_AnimalNumber");

                    b.ToTable("Animals", (string)null);
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Animals.MovementEvent", b =>
                {
                    b.Property<long>("MovementEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("MovementEventId"));

                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementReason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecordedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Manual");

                    b.Property<DateTime>("StartUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("MovementEventId");

                    b.HasIndex("AnimalId")
                        .IsUnique()
                        .HasDatabaseName("UX_MovementEvents_OneOpenStayPerAnimal")
                        .HasFilter("[EndUtc] IS NULL");

                    b.HasIndex("LocationId", "AnimalId")
                        .HasDatabaseName("IX_MovementEvents_OpenByLocation")
                        .HasFilter("[EndUtc] IS NULL");

                    b.HasIndex("AnimalId", "StartUtc", "EndUtc", "LocationId")
                        .IsDescending(true, false, false, false)
                        .HasDatabaseName("IX_MovementEvents_Animal_Start_End");

                    b.HasIndex("LocationId", "StartUtc", "EndUtc", "AnimalId")
                        .HasDatabaseName("IX_MovementEvents_Location_Start_End");

                    b.ToTable("MovementEvents", null, t =>
                        {
                            t.HasCheckConstraint("CK_MovementEvents_EndAfterStart", "[EndUtc] IS NULL OR [EndUtc] > [StartUtc]");

                            t.HasCheckConstraint("CK_MovementEvents_SourceType", "[SourceType] IN (N'Manual', N'Import', N'Derived')");
                        });
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Facilities.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("FacilityCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("FacilityId");

                    b.HasIndex("FacilityCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Facilities_FacilityCode");

                    b.ToTable("Facilities", (string)null);
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Imports.ImportBatch", b =>
                {
                    b.Property<long>("ImportBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImportBatchId"));

                    b.Property<string>("BatchType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExecutedByUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("RunMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceFileHash")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("SourceFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("nvarchar(260)");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Summary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImportBatchId");

                    b.HasIndex("FacilityId");

                    b.ToTable("ImportBatches", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImportBatches_RunMode", "[RunMode] IN (N'ValidateOnly', N'Commit')");

                            t.HasCheckConstraint("CK_ImportBatches_Status", "[Status] IN (N'Pending', N'Failed', N'Succeeded')");
                        });
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Imports.ImportIssue", b =>
                {
                    b.Property<long>("ImportIssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ImportIssueId"));

                    b.Property<long>("ImportBatchId")
                        .HasColumnType("bigint");

                    b.Property<string>("ItemKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SheetName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ImportIssueId");

                    b.HasIndex("ImportBatchId");

                    b.ToTable("ImportIssues", null, t =>
                        {
                            t.HasCheckConstraint("CK_ImportIssues_Severity", "[Severity] IN (N'Error', N'Warning')");
                        });
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Locations.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int?>("GridColumn")
                        .HasColumnType("int");

                    b.Property<int?>("GridRow")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LocationType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("ParentLocationId")
                        .HasColumnType("int");

                    b.Property<int>("StackLevel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("LocationId");

                    b.HasAlternateKey("LocationId", "FacilityId")
                        .HasName("UQ_Locations_LocationId_Facility");

                    b.HasIndex("FacilityId", "LocationCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Locations_Facility_LocationCode");

                    b.HasIndex("ParentLocationId", "FacilityId");

                    b.HasIndex("FacilityId", "LocationType", "IsActive")
                        .HasDatabaseName("IX_Locations_Facility_Type_Active");

                    b.HasIndex("ParentLocationId", "DisplayOrder", "Name")
                        .HasDatabaseName("IX_Locations_Parent_DisplayOrder");

                    b.HasIndex("FacilityId", "ParentLocationId", "IsActive", "LocationType")
                        .HasDatabaseName("IX_Locations_Facility_Parent");

                    b.HasIndex("ParentLocationId", "GridRow", "GridColumn", "StackLevel")
                        .IsUnique()
                        .HasDatabaseName("UX_Locations_ActiveKennelGridPosition")
                        .HasFilter("[LocationType] = N'Kennel' AND [IsActive] = 1 AND [ParentLocationId] IS NOT NULL AND [GridRow] IS NOT NULL AND [GridColumn] IS NOT NULL");

                    b.ToTable("Locations", null, t =>
                        {
                            t.HasCheckConstraint("CK_Locations_GridColumn", "[GridColumn] IS NULL OR [GridColumn] >= 0");

                            t.HasCheckConstraint("CK_Locations_GridCoordinatesTogether", "([GridRow] IS NULL AND [GridColumn] IS NULL) OR ([GridRow] IS NOT NULL AND [GridColumn] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Locations_GridRow", "[GridRow] IS NULL OR [GridRow] >= 0");

                            t.HasCheckConstraint("CK_Locations_KennelHasParent", "[LocationType] <> N'Kennel' OR [ParentLocationId] IS NOT NULL");

                            t.HasCheckConstraint("CK_Locations_LocationType", "[LocationType] IN (N'Room', N'Hallway', N'Medical', N'Isolation', N'Intake', N'Yard', N'Kennel', N'Other')");

                            t.HasCheckConstraint("CK_Locations_NotOwnParent", "[ParentLocationId] IS NULL OR [ParentLocationId] <> [LocationId]");

                            t.HasCheckConstraint("CK_Locations_StackLevel", "[StackLevel] >= 0");
                        });
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Locations.LocationLink", b =>
                {
                    b.Property<int>("LocationLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationLinkId"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<int>("FromLocationId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LinkType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("SourceReference")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Manual");

                    b.Property<int>("ToLocationId")
                        .HasColumnType("int");

                    b.HasKey("LocationLinkId");

                    b.HasIndex("FromLocationId", "FacilityId");

                    b.HasIndex("ToLocationId", "FacilityId");

                    b.HasIndex("FacilityId", "LinkType", "IsActive")
                        .HasDatabaseName("IX_LocationLinks_Facility_Type_Active");

                    b.HasIndex("FromLocationId", "LinkType", "IsActive")
                        .HasDatabaseName("IX_LocationLinks_From_Type_Active");

                    b.HasIndex("FromLocationId", "ToLocationId", "LinkType")
                        .IsUnique()
                        .HasDatabaseName("UX_LocationLinks_ActiveDirected")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("ToLocationId", "LinkType", "IsActive")
                        .HasDatabaseName("IX_LocationLinks_To_Type_Active");

                    b.ToTable("LocationLinks", null, t =>
                        {
                            t.HasCheckConstraint("CK_LocationLinks_LinkType", "[LinkType] IN (N'AdjacentLeft', N'AdjacentRight', N'AdjacentAbove', N'AdjacentBelow', N'AdjacentOther', N'Connected', N'Airflow', N'TransportPath')");

                            t.HasCheckConstraint("CK_LocationLinks_NotSelf", "[FromLocationId] <> [ToLocationId]");

                            t.HasCheckConstraint("CK_LocationLinks_SourceType", "[SourceType] IN (N'Manual', N'Import', N'Derived')");
                        });
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Tracing.Disease", b =>
                {
                    b.Property<int>("DiseaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiseaseId"));

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiseaseCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("DiseaseId");

                    b.HasIndex("DiseaseCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_Diseases_DiseaseCode");

                    b.ToTable("Diseases", (string)null);
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Tracing.DiseaseTraceProfile", b =>
                {
                    b.Property<int>("DiseaseTraceProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DiseaseTraceProfileId"));

                    b.Property<int>("AdjacencyDepth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefaultLookbackHours")
                        .HasColumnType("int");

                    b.Property<int>("DiseaseId")
                        .HasColumnType("int");

                    b.Property<bool>("IncludeAdjacent")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IncludeSameLocation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IncludeSameRoom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IncludeTopologyLinks")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("ModifiedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("TopologyDepth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("DiseaseTraceProfileId");

                    b.HasIndex("DiseaseId")
                        .IsUnique()
                        .HasDatabaseName("UQ_DiseaseTraceProfiles_Disease");

                    b.HasIndex("DiseaseId", "IsActive")
                        .HasDatabaseName("IX_DiseaseTraceProfiles_Disease_Active");

                    b.ToTable("DiseaseTraceProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_DiseaseTraceProfiles_AdjacencySettings", "([IncludeAdjacent] = 0 AND [AdjacencyDepth] = 0) OR ([IncludeAdjacent] = 1 AND [AdjacencyDepth] > 0)");

                            t.HasCheckConstraint("CK_DiseaseTraceProfiles_Lookback", "[DefaultLookbackHours] > 0");

                            t.HasCheckConstraint("CK_DiseaseTraceProfiles_TopologySettings", "([IncludeTopologyLinks] = 0 AND [TopologyDepth] = 0) OR ([IncludeTopologyLinks] = 1 AND [TopologyDepth] > 0)");
                        });
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Tracing.DiseaseTraceProfileTopologyLinkType", b =>
                {
                    b.Property<int>("DiseaseTraceProfileId")
                        .HasColumnType("int");

                    b.Property<string>("LinkType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("DiseaseTraceProfileId", "LinkType")
                        .HasName("PK_DiseaseTraceProfileTopologyLinkTypes");

                    b.ToTable("DiseaseTraceProfileTopologyLinkTypes", null, t =>
                        {
                            t.HasCheckConstraint("CK_DiseaseTraceProfileTopologyLinkTypes_LinkType", "[LinkType] IN (N'Connected', N'Airflow', N'TransportPath')");
                        });
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Animals.MovementEvent", b =>
                {
                    b.HasOne("KennelTrace.Domain.Features.Animals.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MovementEvents_Animals");

                    b.HasOne("KennelTrace.Domain.Features.Locations.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_MovementEvents_Locations");
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Imports.ImportBatch", b =>
                {
                    b.HasOne("KennelTrace.Domain.Features.Facilities.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_ImportBatches_Facilities");
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Imports.ImportIssue", b =>
                {
                    b.HasOne("KennelTrace.Domain.Features.Imports.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("ImportBatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ImportIssues_ImportBatches");
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Locations.Location", b =>
                {
                    b.HasOne("KennelTrace.Domain.Features.Facilities.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Locations_Facilities");

                    b.HasOne("KennelTrace.Domain.Features.Locations.Location", "ParentLocation")
                        .WithMany("Children")
                        .HasForeignKey("ParentLocationId", "FacilityId")
                        .HasPrincipalKey("LocationId", "FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("FK_Locations_ParentSameFacility");

                    b.Navigation("ParentLocation");
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Locations.LocationLink", b =>
                {
                    b.HasOne("KennelTrace.Domain.Features.Facilities.Facility", null)
                        .WithMany()
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LocationLinks_Facilities");

                    b.HasOne("KennelTrace.Domain.Features.Locations.Location", null)
                        .WithMany()
                        .HasForeignKey("FromLocationId", "FacilityId")
                        .HasPrincipalKey("LocationId", "FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LocationLinks_FromLocationSameFacility");

                    b.HasOne("KennelTrace.Domain.Features.Locations.Location", null)
                        .WithMany()
                        .HasForeignKey("ToLocationId", "FacilityId")
                        .HasPrincipalKey("LocationId", "FacilityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_LocationLinks_ToLocationSameFacility");
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Tracing.DiseaseTraceProfile", b =>
                {
                    b.HasOne("KennelTrace.Domain.Features.Tracing.Disease", null)
                        .WithMany()
                        .HasForeignKey("DiseaseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_DiseaseTraceProfiles_Diseases");
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Tracing.DiseaseTraceProfileTopologyLinkType", b =>
                {
                    b.HasOne("KennelTrace.Domain.Features.Tracing.DiseaseTraceProfile", null)
                        .WithMany("TopologyLinkTypes")
                        .HasForeignKey("DiseaseTraceProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_DiseaseTraceProfileTopologyLinkTypes_Profile");
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Locations.Location", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("KennelTrace.Domain.Features.Tracing.DiseaseTraceProfile", b =>
                {
                    b.Navigation("TopologyLinkTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
